name: Jira extract issues by tags
description: Extract issue keys from commit messages
branding:
  color: blue
  icon: git-commit
inputs:
  token:
    description: Your Github token
    required: true
  head-tag:
    description: The head tag, in format xxx_v1.1.0 || v1.1.0 || 1.1.0 || 1.1
    required: true
  release-tag:
    description: The release tag, defaults to previous semver if not specified
    required: false
  continue-on-error:
    required: false
    default: false
ouputs:
  issue-keys:
    description: All issue keys, separated by a comma
runs:
  using: 'node12'
  main: 'dist/index.js'

